# Generated by Django 5.2.7 on 2026-05-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="部门编码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="部门名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新增"),
                            ("update", "修改"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("business", "业务操作"),
                        ],
                        max_length=32,
                        verbose_name="动作",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=64, verbose_name="对象类型"),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=64, verbose_name="对象ID"),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="对象名称"
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="摘要")),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
