# Generated by Django 5.2.7 on 2026-05-20 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="分类编码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="分类名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="assets.assetcategory",
                        verbose_name="上级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产分类",
                "verbose_name_plural": "资产分类",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="资产编号"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="资产名称")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=64, verbose_name="品牌"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=64, verbose_name="型号"),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="规格参数"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="购买日期"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="购买价格",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="存放位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "闲置"),
                            ("in_use", "使用中"),
                            ("repairing", "维修中"),
                            ("scrapped", "已报废"),
                        ],
                        default="idle",
                        max_length=24,
                        verbose_name="资产状态",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.department",
                        verbose_name="使用部门",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                        verbose_name="资产分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="领用用途"
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="领用时间"
                    ),
                ),
                (
                    "expected_return_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预计归还时间"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际归还时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrowed", "借出中"),
                            ("returned", "已归还"),
                            ("overdue", "已逾期"),
                        ],
                        default="borrowed",
                        max_length=24,
                        verbose_name="记录状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="领用人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to="core.department",
                        verbose_name="领用部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "领用归还记录",
                "verbose_name_plural": "领用归还记录",
                "ordering": ["-borrowed_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("issue_description", models.TextField(verbose_name="故障描述")),
                (
                    "maintenance_vendor",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="维修单位"
                    ),
                ),
                (
                    "maintainer",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="维修人员"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="维修结果")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="维修费用",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待维修"),
                            ("processing", "维修中"),
                            ("done", "已完成"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="维修状态",
                    ),
                ),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="报修人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产维修记录",
                "verbose_name_plural": "资产维修记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="申请时间"
                    ),
                ),
                ("reason", models.TextField(verbose_name="报废原因")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "disposal_note",
                    models.TextField(blank=True, verbose_name="处理说明"),
                ),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scrap_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrap_records",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产报废记录",
                "verbose_name_plural": "资产报废记录",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "transferred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="调拨时间"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="调拨原因"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "extension_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_records",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_out_records",
                        to="core.department",
                        verbose_name="调出部门",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_out_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="原使用人",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_transfer_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_in_records",
                        to="core.department",
                        verbose_name="调入部门",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_in_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="新使用人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产调拨记录",
                "verbose_name_plural": "资产调拨记录",
                "ordering": ["-transferred_at"],
            },
        ),
    ]
