# Generated by Django 5.2.7 on 2026-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('base_url', models.CharField(default='https://api.deepseek.com', max_length=255, verbose_name='API Base URL')),
                ('model', models.CharField(default='deepseek-chat', max_length=64, verbose_name='模型名称')),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
